# Generated by Django 4.2.3 on 2023-08-08 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('audience', models.TextField()),
                ('cost', models.TextField()),
                ('travel_date', models.TextField()),
                ('location', models.TextField()),
                ('itinerary_notes', models.TextField()),
                ('image', models.URLField()),
                ('date_created', models.DateTimeField()),
                ('creator', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giver', models.CharField(max_length=200)),
                ('anonymous', models.BooleanField()),
                ('comment', models.CharField(max_length=200)),
                ('reward_date', models.DateTimeField()),
                ('itinerary_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='itineraries.itinerary')),
            ],
        ),
    ]
