# Generated by Django 4.2.3 on 2023-08-07 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giver', models.CharField(max_length=200)),
                ('anonymous', models.BooleanField()),
                ('comment', models.CharField(max_length=200)),
                ('Reward_date', models.DateTimeField()),
                ('itinerary_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='itineraries.itinerary')),
            ],
        ),
    ]
