# Generated by Django 4.2.3 on 2023-08-08 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itineraries', '0002_alter_itinerary_creator_alter_reward_giver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='giver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_rewards', to=settings.AUTH_USER_MODEL),
        ),
    ]
