# Generated by Django 4.2.3 on 2023-08-07 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0002_reward'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reward',
            old_name='Reward_date',
            new_name='reward_date',
        ),
    ]
