# Generated by Django 4.2.3 on 2023-08-08 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0004_alter_reward_giver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='anonymous',
        ),
    ]
