# Generated by Django 4.2.3 on 2023-08-12 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0007_rename_itinerary_id_reward_itinerary'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
