# Generated by Django 4.2.3 on 2023-08-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0008_reward_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='anonymous',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
